### ISSUE TITLE
usb header is close to usb port 

### ISSUE THREAD

**Issue by CarlFK** [mithro/MoBoControl#3]
depending on the size of the plug, there might not be enough room to plug it - the back of the usb port is close.

I was able to plug in a ribbon cable I happen to have, but only in 1 orientation.  The key tab on the other side makes it impossible to plug in that way.  (which might be a feature if the usb ribbon cable is keyed such that we can't plug it in backwards

**Comment by anfroholic** [comment]
Done 
![image](https://github.com/mithro/MoBoControl/assets/1464801/c15fa5f4-cc12-4b10-82a5-0814137e59f6)

**Comment by CarlFK** [comment]
yup.
